// Generated by CoffeeScript undefined
var React;

React = require('react');

module.exports = React.createClass({
  displayName: "SpinKit",
  render: function() {
    return this.transferPropsTo(React.DOM.div({
      "className": "spinner pulse"
    }));
  }
});
